#include <iostream>
#include <stdio.h>
#include <string>
#include <vector>
#include <cstdio>
#include <float.h>
#include <istream>
#include <ostream>
#include <tuple>
#include <algorithm>
#include <bitset>
#include <iomanip>
#include <cmath>
#include <sstream>
#include <cstdint>
#include <fstream>